apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: nginx-ingress
  repo: https://helm.nginx.com/stable
  releaseName: mvd
  namespace: nginx
  valuesInline:
    controller:
      replicaCount: 3
    
