apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: nginx-ingress
  version: 0.16.1
  repo: https://helm.nginx.com/stable
  releaseName: nginx
  namespace: nginx
  valuesInline:
    controller:
      replicaCount: 3
    
